# ./services/api/Dockerfile.api
FROM python:3.10-slim

WORKDIR /app

# Instalar dependencias
RUN pip install fastapi uvicorn requests qdrant-client redis

# Copiar scripts
COPY ./scripts ./scripts/

# Copiar main.py
COPY /api/main.py .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]