log_level: INFO

storage:
  storage_path: "/qdrant/storage"
  optimizers:
    indexing_threshold_kb: 10000   # 👈 correcto
    memmap_threshold_kb: 20000     # 👈 también usa _kb
    max_optimization_threads: 2
  cache_size: 2048
  snapshots:
    enabled: false
    #interval_seconds: 3600

performance:
  search_queue_size: 100
  update_queue_size: 100
  flush_interval_sec: 1

service:
  http_port: 6333
  grpc_port: 6334
  max_request_size_mb: 32
  max_workers: 4

